# Generated by Django 3.2.9 on 2022-05-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_portal', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='country',
            name='death',
        ),
        migrations.RemoveField(
            model_name='country',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='country',
            name='todaysCases',
        ),
    ]
