# Generated by Django 3.2.9 on 2022-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_portal', '0003_auto_20220502_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='text',
        ),
    ]
