# Generated by Django 3.2.9 on 2022-05-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_portal', '0004_rename_country_name_country_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='text',
            new_name='country_name',
        ),
    ]
