# Generated by Django 3.2.9 on 2022-05-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_portal', '0005_rename_text_country_country_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
