# Generated by Django 4.0.4 on 2022-05-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_portal', '0006_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
